# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_painted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
        ),
    ]
